### ISSUE TITLE
Missing Exceptions

### ISSUE THREAD

**Issue by stelgenhof** [RoyVoetman/flysystem-gitlab-storage#1]
Thanks for the great package! Could you provide some additional exception handling (i.e throw errors)? Various API methods return a false or an empty array in case there is an (Guzzle) issue.

It makes it hard to assess if something is wrong on the Gitlab end or if really the result is empty. 

For example, I didn't get any results, as it turned out that my private token didn't have the proper access levels.

Cheers! Sacha

**Comment by RoyVoetman** [comment]
A debug mode is now added to version 1.0.7: https://github.com/RoyVoetman/flysystem-gitlab-storage/releases/tag/v1.0.7
