### ISSUE TITLE
listContents only returns limited number of files

### ISSUE THREAD

**Issue by stelgenhof** [RoyVoetman/flysystem-gitlab-storage#4]
The listContents method only returns a limited number of files. In my folder I have for example 32 files, but the returning array only contains 20 items. 

Looking at the code, this makes sense as the Gitlab API parameters `per_page` or `page` are not implemented and the  default number of results is 20 if not specified. See here: https://docs.gitlab.com/ee/api/repositories.html#list-repository-tree

Would be nice if pagination could be supported to allow for retrieving larger number of results.
See also here: https://docs.gitlab.com/ee/api/README.html#pagination

**Comment by RoyVoetman** [comment]
This has now been resolved in version 1.1.0.

The per_page parameter has been updated to a maximum of 100. When there are more than 100 entries they will be retrieved automatically by iterating over all the pages. This is done by examining the X-Next-Page header returned by the Gitlab API.

**Comment by stelgenhof** [comment]
Thanks for implementing this so quickly!
